### ISSUE TITLE
Fetching channel emoticon metadata hanging

### ISSUE THREAD

**Issue by theycallmemac** [dongy7/twitch-chat-cli#1]
Hi there, first off thanks for building this it's a brilliant idea!

Running into an issue at the moment when fetching channel emoticon metadata.

I've used `docker-compose up -d` to run the API server on port 3000 and it seems to be fine, this is what I get from `docker-compose ps`:

```
     Name                   Command               State           Ports
--------------------------------------------------------------------------------
api_app_1        docker-entrypoint.sh npm start   Up      0.0.0.0:3000->3000/tcp
api_postgres_1   docker-entrypoint.sh postgres    Up      0.0.0.0:5432->5432/tcp
```

Once I use `tc connect theycallmemac_` however I get the following response:

```
✔ Checking for emoticon api.
⠏ Fetching channel emoticon metadata.

```

It just seems to hang forever while it attempts to fetch the emoticon metadata. If I stop the container, it works fine again.

Any ideas why this may be happening?

**Comment by dongy7** [comment]
Did you clone the repo with Git LFS installed? The `api/seed/emotes.bak` file should be around ~20mb or so. I've also updated the Docker configuration files as there seemed to be some issues with the Node server failing to connect to the database. Also, it looks like the endpoint that I was using at the time to get the channel emotes (https://static-cdn.jtvnw.net/emoticons/v1/) seems to have changed so I will see if I can get that updated as well.

**Comment by dongy7** [comment]
I've updated the endpoint so fetching the emotes should work again.

**Comment by theycallmemac** [comment]
Running the new files and checking with ```docker-compose ps``` I get the following:

```
     Name                   Command               State            Ports
---------------------------------------------------------------------------------
api_app_1        docker-entrypoint.sh ./wai ...   Exit 1
api_postgres_1   docker-entrypoint.sh postgres    Up       0.0.0.0:5432->5432/tcp
```

If I check the logs of ```api_app_1``` I get this:

```
internal/modules/cjs/loader.js:957
    throw err;
    ^

Error: Cannot find module '/app/wait-for-it.sh'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:957
    throw err;
    ^

Error: Cannot find module '/app/wait-for-it.sh'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by theycallmemac** [comment]
Let me know what you think on this :)
